name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # Set to your default branch name

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      # Install Hugo directly without using peaceiris/actions-hugo
      - name: Setup Hugo
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.123.6/hugo_extended_0.123.6_linux-amd64.deb
          sudo dpkg -i ${{ runner.temp }}/hugo.deb
          hugo version

      - name: Build
        run: hugo --minify

      # Deploy directly to GitHub Pages branch instead of using actions/upload-pages-artifact and actions/deploy-pages
      - name: Deploy to GitHub Pages
        run: |
          cd public
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git init
          git add .
          git commit -m "Deploy Hugo site"
          git push --force "https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git" main:gh-pages